#!/usr/bin/env python

import ConfigParser
import argparse
import json
from cmdb_libs.audit import YumHandler, FacterHandler, HostMetadata
from cmdb_libs.dynamo import DynamoHandler



def argparser():
    parser = argparse.ArgumentParser()
    parser.add_argument('-o', '--output', choices=['stdout', 'dynamo'], default='stdout',
                        help='where to output the results')
    parsed_args = parser.parse_args()
    return vars(parsed_args)


if __name__ == '__main__':
    # TODO: unify the config
    args = argparser()
    instance_id = HostMetadata().get()
    rpm_packages = YumHandler().get()
    facts = FacterHandler().get()

    results = {
        'instance_id': instance_id,
        'rpm_packages': rpm_packages,
        'facts': facts,
    }

    if args['output'] == 'stdout':
        print json.dumps(results, indent=4)
    elif args['output'] == 'dynamo':
        dh = DynamoHandler()
        dh.post_audit(instance_id, results)
